[[mgr.prepend_keymap]]
on = "j"
run = [ "arrow 1", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Down + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "k"
run = [ "arrow -1", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Up + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<Down>"
run = [ "arrow 1", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Down + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<Up>"
run = [ "arrow -1", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Up + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<PageDown>"
run = [ "arrow 50%", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "PageDown + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<PageUp>"
run = [ "arrow -50%", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "PageUp + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = [ "arrow 50%", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Half page down + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<C-u>"
run = [ "arrow -50%", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Half page up + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = [ "g", "g" ]
run = [ "arrow top", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Top + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "G"
run = [ "arrow bot", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Bottom + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<Home>"
run = [ "arrow top", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "Home + Kakoune preview sync"

[[mgr.prepend_keymap]]
on = "<End>"
run = [ "arrow bot", 'shell "$HOME/.local/bin/kak-preview-sync %h" --orphan' ]
desc = "End + Kakoune preview sync"
