# prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# mouse
set -g mouse on

# clipboard
set -g set-clipboard on

# index
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# border
set -g pane-border-style fg=white
set -g pane-active-border-style fg=green

# pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# split
bind-key v split-window -h
bind-key s split-window -v

# reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# kak-preview-sync env sync
set -ga update-environment "TMPDIR"
set -ga update-environment "XDG_RUNTIME_DIR"

# tmux plugin manager and session persistence
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# resurrect / continuum
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'
set -g @continuum-save-interval '15'

run '~/.tmux/plugins/tpm/tpm'
